---
# file: roles/dbtier/tasks/mysql.yml
- name: Install package for MySQL community edition repository
  tags: mysql
  yum:
    name: "http://repo.mysql.com/mysql-community-release-el{{ ansible_distribution_major_version }}-5.noarch.rpm"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install MySQL
  tags: mysql
  yum: name=mysql-server state=installed
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install MySQL
  tags: mysql
  apt: name=mysql-server state=installed
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Make sure MySQL is running and started on boot
  tags: mysql
  service: name=mysqld state=started enabled=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Make sure MySQL is running and started on boot
  tags: mysql
  service: name=mysql state=started enabled=yes
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install MySQL-python
  tags: mysql
  yum: name=MySQL-python state=installed
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

- name: Install MySQL-python
  tags: mysql
  apt: name=python-mysqldb state=installed
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Copy .my.cnf file with root password credentials
  tags: mysql
  template: src=my-credentials.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: Update mysql root password for all root accounts
  tags: mysql
  mysql_user: check_implicit_admin=yes name=root host=localhost password={{ mysql_root_password }}

#- name: Install MySQL 5.7 from EPEL
#  yum:
#    name: "{{ item }}"
#    state: present
#    enablerepo: epel
#  with_items:
#   - mysql57-server
#   - MySQL-python27
#   - libselinux-python
#   - libsemanage-python

#- name: Create Mysql configuration file
#  template:
#    src: my.cnf.j2
#    dest: /etc/my.cnf
#  notify:
#  - restart mysql


- name: Create DB user for Magento
  mysql_user:
    name: "{{ magento_db_user }}"
    password: "{{ magento_db_password }}"
    priv: '*.*:ALL'
    state: present

- name: Create DB schema for Magento
  mysql_db:
    name: "{{ magento_db_name }}"
    state: present
